default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/psf/black
    rev: 88d12f88a97e5e4c8fd0d245df0a311e932fd1e1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f0bf512dbb1a9a23ce022551b31fbfc54be8cd0d
    hooks:
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: b08e15c922b6700c850d69d2df7c3b6b6dc3f116
    hooks:
      - id: isort

  - repo: https://github.com/asottile/add-trailing-comma
    rev: 4737c82eefc7cbe6028bb5e2fc6619a38cd0de76
    hooks:
      - id: add-trailing-comma